name: Check IT Passport

on:
  schedule:
    - cron: '0 * * * *'  # 1時間ごとの実行
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pdfplumber requests

    - name: Run script
      run: python main.py
